language: node_js
node_js:
  - "4.3.2"
  - "5"
  - "6.9"
  - "7"

script: echo "Running tests against $(node -v) ..."

deploy:
  provider: npm
  email: "admin@jwije.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true  

