language: node_js

node_js: ['6', '7']

install:
- yarn
- yarn build

script:
- yarn lint
- yarn build
- yarn test
- yarn test:bench

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm publish
  on:
    tags: true
