language: node_js
node_js:
  - "6.10.2"
  - "7"

install:
  - yarn
  - yarn build

script:
  - yarn test
  - yarn test:boundry
  - yarn benchmark

deploy:
  provider: npm
  email: "admin@jwije.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true  

